sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
    - master

services: docker

env:
  matrix:
    #  - INSTANCE=resource-test-amazonlinux
  - INSTANCE=resource-test-centos-6
  - INSTANCE=resource-test-centos-7
  - INSTANCE=resource-test-debian-7
  - INSTANCE=resource-test-debian-8
  - INSTANCE=resource-test-debian-9
    #  - INSTANCE=resource-test-opensuse-leap
  - INSTANCE=resource-test-ubuntu-1404
  - INSTANCE=resource-test-ubuntu-1604

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

script: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - chef exec delivery local all
      env: UNIT_AND_LINT=1
